from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Integer, JSON, String, Text
from app.database.database import Base


class Analysis(Base):
    __tablename__ = "analyses"

    id = Column(Integer, primary_key=True, index=True)

    prompt = Column(Text, nullable=False)

    risk_score = Column(Integer, nullable=False)

    severity = Column(String, nullable=False)

    # Executive summary shown to the user
    summary = Column(Text, nullable=True)

    # Detailed business impact
    business_impact = Column(Text, nullable=True)

    # Attack scenario generated by AI
    attack_scenario = Column(Text, nullable=True)

    # Secure rewritten prompt
    secure_prompt = Column(Text, nullable=True)

    # OWASP LLM category
    owasp = Column(String, nullable=True)

    # AI recommendations
    recommendations = Column(JSON, nullable=True)

    # Backward compatibility
    message = Column(Text, nullable=True)

    detections = Column(JSON, nullable=True)

    ai_confidence = Column(Integer, nullable=True)

    analysis_engine = Column(
        String,
        default="Rule Engine + Gemini AI",
    )

    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )